export const ROUTE_NAMES = Object.freeze({
  LANDING: 'landing',
  LOGIN: 'login',
  SIGNUP: 'signup',
  FORGOT_PASSWORD: 'forgot-password',
  DASHBOARD: 'dashboard',
  ADMIN: 'admin',
  RESUMES: 'resumes',
  RESUME_NEW: 'resume-new',
  RESUME_EDIT: 'resume-edit',
  COMING_SOON: 'coming-soon',
  PROFILE: 'profile',
  SETTINGS: 'settings',
  ABOUT: 'about',
  CAREERS: 'careers',
  BLOG: 'blog',
  CONTACT: 'contact',
  HELP: 'help',
  FAQ: 'faq',
  SUPPORT: 'support',
  STATUS: 'status',
  PRIVACY: 'privacy',
  TERMS: 'terms',
  COOKIES: 'cookies',
  REFUND: 'refund',
  SHIPPING: 'shipping'
})
